workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set executable permission for gradlew
        script: chmod +x ./gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com # این آدرس را با ایمیل خود جایگزین کنید