name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build APK
      run: ./gradlew assembleDebug --info
      
    - name: List generated files
      run: |
        echo "Generated files:"
        find . -name "*.apk"
      
    - name: Create release folder
      run: mkdir -p release
    
    - name: Copy APK to release folder
      run: find . -name "*.apk" -exec cp {} release/ \;
    
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: release/