name: Simple CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create simple file
      run: |
        mkdir -p artifact
        echo "This is a simple file created by GitHub Actions" > artifact/simple.txt
        echo "Project: CryptoPriceMonitor" >> artifact/simple.txt
        echo "Date: $(date)" >> artifact/simple.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: simple-artifact
        path: artifact