name: Android Build Log

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Display project structure
      run: |
        echo "Project structure:"
        ls -la
        
    - name: Check gradle files
      run: |
        echo "Gradle files:"
        find . -name "*.gradle" | sort
        
    - name: Check build files
      run: |
        echo "Checking build files:"
        cat build.gradle || echo "No root build.gradle found"
        cat app/build.gradle || echo "No app/build.gradle found"
        cat settings.gradle || echo "No settings.gradle found"
        
    - name: Show README
      run: cat README.md