name: Basic CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run simple commands
      run: |
        echo "Hello from GitHub Actions!"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch: $GITHUB_REF"
        echo "Current directory: $(pwd)"
        ls -la
        
    - name: Display project structure
      run: |
        echo "Project structure:"
        find . -type f -name "*.md" | sort