name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Use pre-built APK template
      run: |
        mkdir -p app/build/outputs/apk/debug
        curl -L https://github.com/android/android-studio-poet/raw/main/aspoet/sample/app-debug.apk -o app/build/outputs/apk/debug/app-debug.apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk